---

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- { include: Debian.yml, when: "ansible_os_family == 'Debian'", static: no }
- { include: RedHat.yml, when: "ansible_os_family == 'RedHat'", static: no }

- { include: config-RedHat6.yml, when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6", static: no }
- { include: config-RedHat6.yml, when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'", static: no }
- { include: config-RedHat.yml,  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int  > 6", static: no }
- { include: config-other.yml,   when: "ansible_os_family != 'RedHat' and ansible_distribution_version != '12.04'", static: no }

- name: create conf.d folder for configuration file
  file: path='/etc/syslog-ng/conf.d' state=directory owner=root group=root mode=0755

- name: add remote configuration file
  template: src=remote.conf.j2 dest='/etc/syslog-ng/conf.d/remote.conf' owner=root group=root mode=0644
  notify:
   - restart syslog-ng
